---
- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Updating apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Deploy Docker Container
      shell: docker run -itd -p 8084:8081 kranthi619/finance-me:latest


