---
- name: Configure Docker on Deployserver
  hosts: all
  become: true
  connection : ssh
  tasks:
    - name: apt updating
      apt: update_cache=yes

    - name: Install python and Pip
      apt:
        name: python-pip
        state: present

    - name: Installing Docker
      apt:
        name: docker.io
        state: present
      become: true

    - name: Start Docker service using systemctl
      systemd:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: Deploy the image and Run as a container
      command: docker run -itd -p 8084:8080 kranthi619/insure-me:latest
      become: true





