- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Python
    apt:
      name: python-pip
      state: present

  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Start Docker Service
    service:
      name: docker
      state: started

  - name: Deploy the image and run as a container
    command: docker run -itd -p 8084:8081 kranthi619/insure-me:latest


